[theme]
base = "dark"
primaryColor = "#7CFC00"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#00FF41"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
