[theme]
base = "dark"
primaryColor = "#00c896"               # Soft teal accent
backgroundColor = "#0f1620"            # Deep midnight blue
secondaryBackgroundColor = "#1b2430"   # Slight contrast for cards, panels
textColor = "#E2E8F0"                  # Soft white-gray
font = "monospace"                     # Terminal aesthetic
